### ISSUE TITLE
Volspotconnect2.zip not installing

### ISSUE THREAD

**Issue by psychophil** [balbuze/volumio-plugins#40] opened 2017-04-09 08:34 UTC
Sorry but never used  a bug report before and know little about programming.

Up until end of February your plugin worked. I decided to do a fresh volumio2 install. I'm using pi3 and version 2.138. I've also tried Pi2 and B+ models with same error shown below.

Installing dependencies
Installing spotify-connect-web dependencies
Detecting cpu
Cpu is armv7l, downloading required package.
Failed to download. Stopping installation now
The following error occurred when installing the plugin: Error

**Comment by balbuze** [comment] 2017-04-09 09:04
Hi,
This is due to a network problem. Several reasons:
- Your connection failed
- github server does not respond
The only thing is to retry.
A other user had the same problem last weekend.

**Comment by psychophil** [comment] 2017-04-09 09:11
Thanks for quick response.

This has been going on for over a week. Unfortunately I've deleted older
install and files. Is there another way to get a pre installed image or
necessary files?

**Comment by balbuze** [comment] 2017-04-09 09:16
The problem doesn't come from the version. And there is no other way to install easily. But you can have a look in install.sh in the plugin and change the downloaded package path for a local one you would have downloaded.....
But really just retry until it works. ...

**Comment by mundodisco8** [comment] 2017-04-10 10:05
I think I had the same issue, had a successful install message, but the plugin was not there. I rebooted and it was on the plugin list. So maybe it needs to refresh a plugin database somewhere?

**Comment by balbuze** [comment] 2017-04-10 11:21
At the end of install, you have to refresh the page in order to see the plugin. No need to reboot. The problem is known and a solution will come.

**Comment by gwlevans** [comment] 2017-04-12 17:45
I managed to fix the not installing issue by changing editing /etc/resolve.conf and commenting out the first two nameserver entries and just leaving the google DNS in place 8.8.8.8 and 8.8.4.4 nameservers.

**Comment by balbuze** [comment] 2017-04-12 19:25
thank for the info. Do you used the menu in volumio / setting / network to do that ?

**Comment by gwlevans** [comment] 2017-04-13 06:32
Initially I edited /etc/resolv.conf directly, which worked but dchpd then overwrote it. So I then used the menu in volumio / settings / network to disable dhcp, set a static address and set the DNS.

**Comment by apinner** [comment] 2017-04-15 07:31
I've tried and tried and tried to install it using all of the suggestions here and I've got nowhere. Always ends with an error.

**Comment by balbuze** [comment] 2017-04-15 07:36
Hi!
I really don't understand what happens...
What is your device ?
If I understand, it detect CPU and after fails to download package ? 
What is the version of volumio?
Do you know the last working version for you ?

**Comment by gwlevans** [comment] 2017-04-15 07:39
If it is a DNS issue that was causing the issue, as was the case for me, try adding the following file via SSH.

/etc/resolv.conf.head

Within it add two lines:

nameserver 8.8.8.8
nameserver 8.8.4.4

You may need to reboot after this, this will tell volumio to use Google DNS before anything it picks up from DHCP, etc.

I hope this help.

**Comment by apinner** [comment] 2017-04-15 07:41
RPi2
Tried it on latest stable and latest development releases of volumio
Not sure what was the last version that worked for me. 

`Downloading plugin at http://127.0.0.1:3000/plugin-serve/f308c39b-5b92-4d12-9452-f1425eed6008.zip
END DOWNLOAD: http://127.0.0.1:3000/plugin-serve/f308c39b-5b92-4d12-9452-f1425eed6008.zip
Creating folder on disk
Unpacking plugin
Checking for duplicate plugin
Copying Plugin into location
Installing dependencies
Installing spotify-connect-web dependencies
Detecting cpu
Cpu is armv7l, downloading required package.
Failed to download. Stopping installation now
The following error occurred when installing the plugin: Error`

Here is the latest log file. http://logs.volumio.org/volumio/jcAbiYo.html

**Comment by gwlevans** [comment] 2017-04-15 08:14
Looks like you are on Virgin Media UK? There is a known issue with their DNS servers and github, etc. See here:

https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=131570

Your DNS is resolving to a Virgin DNS non-authorotive server: 62.252.172.241.

Try the DNS fix I mentioned above. You can't change the DNS servers on the virgin router which is highly annoying!

**Comment by apinner** [comment] 2017-04-15 08:27
@gwlevans nailed it, thanks!

Virgin Media are just shocking..

**Comment by balbuze** [comment] 2017-04-15 08:29
So it does the trick for you ?

**Comment by apinner** [comment] 2017-04-15 08:30
Yep.. Installed fine after i created a resolv.conf.head file with the google name servers.

**Comment by balbuze** [comment] 2017-04-15 09:53
I have changed the error message during installation if it failed with : " Failed to download. Stopping installation now. Check your connection. Thanks your ISP, check DNS settings in Volumio as it may be the cause"

**Comment by gwlevans** [comment] 2017-04-15 11:45
It may be an idea to change the GUI to write the DNS entries to resolv.conf.head if they are set manually in the GUI. This will mean that they are always tried first. I found that resolvconf kept picking up DNS entries from DHCP and using those first even if a manual DNS was configured in the GUI.

**Comment by balbuze** [comment] 2017-04-15 12:26
@gwlevans this point is relevant to volumio, not the plugin. Maybe you could open an issue for that ?

**Comment by gwlevans** [comment] 2017-04-15 12:48
Good point! I have opened an issue on volumio2. New version of the plugin (0.2.9) works a treat with the right DNS entries. Thanks for the great plugin.

**Closed** 2017-04-26 12:30 UTC

**Comment by guille2286** [comment] 2017-06-15 18:28
Hi everyone, 

I've been facing the same problem when trying to install the Volspotconnect2 in my RPi3. The installation process always stops at 70%... 

"Detecting cpu
Cpu is armv7l, downloading required package."

![image](https://user-images.githubusercontent.com/29464817/27195954-05d58d26-5209-11e7-8ef9-d13222cd382c.png)

And it stucks there (no reference to download failure though)

I've tried your suggestions on creating an  /etc/resolv.conf.head file with Gooogl's DNS nameserver 8.8.8.8
and nameserver 8.8.4.4, but still cann't make it work... I'm pretty new at this so any help will be appreciated!
Thanks!

**Comment by macmpi** [comment] 2017-07-07 11:43
Volumio has now proper DNS setting UI, so it is not advised to alter files such as  `/etc/resolv.conf.head` manually, as this may induce unpredictable results. Best it to start from a fresh volumio image and use UI to eventually set DNS.

**Comment by guille2286** [comment] 2017-08-13 16:15
Thanks a lot @macmpi . I've changed the DNS settings using the Volumio's GUI but I'm still getting the same result. 

I've tried downloading the package directly from: https://github.com/balbuze/volumio-plugins/raw/master/plugins/music_service/volspotconnect2/arch/armhf/librespot-armhf.tar.xz

So I'm thinking, is there any way to manually install the plugin?

**Comment by guille2286** [comment] 2017-08-13 18:41
So I finally made it work using the librespot file and volspotconnect2 zip posted by balbuze in another thread: https://github.com/volumio/Volumio2/issues/1123   (may 15). 

Thanks for the support!

**Comment by balbuze** [comment] 2017-08-13 20:22
Ok good!
