### ISSUE TITLE
[volspotconnect2] Status inconsistent

### ISSUE THREAD

**Issue by MateEke** [balbuze/volumio-plugins#145] opened 2018-03-09 08:09 UTC
If I use android phone with the newest version from volumio repo (2018-3-8) the currently played song doesn't appear on the phone, and I don't have any feedback about the play/pause state, etc. on the phone. With the windows 10 version of Spotify it seems fine.

![screenshot_20180308-224637](https://user-images.githubusercontent.com/11072174/37197074-7d5ad10c-2379-11e8-98ba-0d5e436f5c62.jpg)

**Comment by mneedes** [comment] 2018-03-10 21:56
I have the exact or very similar issue.  Volspotconnect 2 works great with the Windows 10 Spotify App, but doesn't sync properly with Android.   The Android App can connect and dispatch commands to the Volumio player, but it doesn't register updates back from the Volumio player.   I can immediately see this when using the forward and back buttons on the Volumio Web Interface (volumio.local).  I am using the 0.6.6 version of the plugin.

**Comment by ashthespy** [comment] 2018-03-13 23:14
Hmm, could you also provide the andorid app version your on? There have been enough reports of this now, that I believe there is something going on that needs some digging!

**Comment by mneedes** [comment] 2018-03-14 04:34
Android Nougat 7.1.1 is what I am using.

**Comment by mneedes** [comment] 2018-03-14 04:36
Spotify App version 8.4.44.661

**Comment by cortegedusage** [comment] 2018-03-14 19:21
Unfortunately i experience the same as above..
But it seems like a bug in the app, because my Chromecast is Having the
same results

Op 14 mrt. 2018 5:36 a.m. schreef "mneedes" <notifications@github.com>:

**Comment by cortegedusage** [comment] 2018-03-14 20:14
and the same when trying to control the spotify web player.

**Comment by cortegedusage** [comment] 2018-03-14 20:27
reverting back to previous  version of android app seems to have solved the problem

**Comment by ashthespy** [comment] 2018-03-14 20:35
@cortegedusage Are you by any chance on Android 8?

**Comment by cortegedusage** [comment] 2018-03-14 20:45
@ashthespy 
good question!

nope android 7.1.2

but it works for me again.
I was running the latest app, It came over the air yesterday.
noticed during the day some anoyance like stated above.
Now reverted back to 
spotify-8-4-1-836.apk

**Comment by MateEke** [comment] 2018-03-14 20:45
Android 8 (Oneplus 5) here, Spotify 8.4.44.661

**Comment by cortegedusage** [comment] 2018-03-14 20:50
@MateEke 
Would be interesting to see if reverting back would solve your problem

**Comment by ashthespy** [comment] 2018-03-14 20:51
@cortegedusage [Interesting](https://volumio.org/forum/spotify-connect-t2811-320.html#p4625) that a downgrade solved your issue ;-.) I will try to reproduce, just upgraded (Android 8 and `8.4.44.661 armv7`)

**Comment by cortegedusage** [comment] 2018-03-14 20:59
@MateEke 
hmm interesting read, I missed that one...
but then again. I downgraded and it works for me, for now anyway.
Would be nice for anyone test it with a chromecast or web player because they 
showed the same behaviour on that latest APK

**Comment by MateEke** [comment] 2018-03-15 17:10
8.4.45.633 still have the issue.

**Comment by cortegedusage** [comment] 2018-03-16 08:29
and indeed, I have to admit the issue is still comming back.
Strange because on a couple of Iphones here  there is no problem
(not sure what version they are running though)
@ashthespy  do you have any lead on what is causing this?
reading your comment on the volumio forum, suggests you might have a clue.
would reverting back the plugin to the point where there was no volumio integration solve this 
issue and hence have working spotify playback with android client?
I'm on the road so cannot test it myself.

**Comment by balbuze** [comment] 2018-03-16 18:11
I'm afraid the new version the Spotify 8.4.45.633 will cause us a lot of headache...
I just updated,and even if it connect and play fine with librespot, buttons disappears in the app, no way to change or stop the player. Weird message such as"start to play" before connecting a device, even if something is played...

**Comment by ashthespy** [comment] 2018-03-17 13:41
@cortegedusage not sure, but I think it could be something to do with how we send back the current state to Spotify (inside librespot). I *think* its fixed with my latest [librespot-armhf.tar.xz](https://files.gitter.im/ashthespy/cezk/librespot-armhf.tar.xz) build. 

I am on (Android 8 and `8.4.44.663 armv7`) and *seems* to work fine :-)

**Comment by cortegedusage** [comment] 2018-03-18 11:02
@ash
Tried yesterday to replace the binairie with yours, but that left me whith
a non working connect device that didn't show up in the app. No time to
investigate further yesterday(damn real life...)thanks for the reply.

Op 17 mrt. 2018 2:41 p.m. schreef "Ash" <notifications@github.com>:

@cortegedusage <https://github.com/cortegedusage> not sure, but I think it
could be something to do with how we send back the current state to Spotify
(inside librespot). I *think* its fixed with my latest
librespot-armhf.tar.xz
<https://files.gitter.im/ashthespy/cezk/librespot-armhf.tar.xz> build.

I am on (Android 8 and 8.4.44.663 armv7) and *seems* to work fine :-)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/balbuze/volumio-plugins/issues/145#issuecomment-373920915>,
or mute the thread

**Comment by balbuze** [comment] 2018-03-18 11:04
You a to set librespot as executable. Sudo chmod +x librespot

**Comment by cortegedusage** [comment] 2018-03-18 11:29
I believe the rights where already good. It did run grom the cli

Op zo 18 mrt. 2018 12:04 schreef balbuze <notifications@github.com>:

**Comment by ashthespy** [comment] 2018-03-18 14:06
@cortegedusage apologies, this isn't a drop in replacement - but is meant to go along with https://github.com/balbuze/volumio-plugins/pull/156 We have not yet packaged it up in a neat zip yet. 

However - since I just was testing on my pi0, here is a small snippet that will sync you up to those changes.
PS - this is experimental/ in progress work on the UI, be warned! :-)
Uninstall the plugin from the plugin manager, then
```
$ wget https://files.gitter.im/ashthespy/Xrht/volspotconnect2.zip
$ mkdir ./volspotconnect2
$ miniunzip volspotconnect2.zip -d ./volspotconnect2
$ cd ./volspotconnect2
$ volumio plugin install
```
Wait while the plugin helper compresses the file again :grimacing:
```
$ cd /data/plugins/music_service/volspotconnect2/
$ wget https://files.gitter.im/ashthespy/cezk/librespot-armhf.tar.xz
$ mv librespot librespot.bak
$ tar -xf librespot-armhf.tar.xz --strip-components 4
```

Enable the plugin from UI!

**Comment by cortegedusage** [comment] 2018-03-18 14:57
@ash yeah thougt so but couldn't find time to check.
(You might think a Little piece of code playing music is a pain in the ass.
I can assure you, real people playing music are even worse)
Will check your suggestion as soon as i can.


Op zo 18 mrt. 2018 15:06 schreef Ash <notifications@github.com>:

**Comment by cortegedusage** [comment] 2018-03-18 15:27
hmm followed your lead, but having the same issues as I had before uninstalling. 
as long as i don't do anything on the UI it keeps playing, but as soon as I skip a track
timer will halt and the track on the APP won't change If I then skip a track it will skip to the next song but the app is one track behind.

you sure I downloaded the right binairy?

**Comment by ashthespy** [comment] 2018-03-18 15:34
@cortegedusage sorry, if I am being a bit dense, but if I understood your problem:

1. From  UI (Volumio WebUI) skip a track 
2. Timer stops (on WebUI), and new track starts playing (reflected on WebUI), 
3. APP still shows old track  
4. Skip song in WebUI
5. APP lags by one song

Hmm - that is strange.
What is the build version/data of the librespot that the plugin is using?

**Comment by cortegedusage** [comment] 2018-03-18 15:41
-rwxr-xr-x  1 volumio volumio 14127488 Mar 15 22:37 librespot

this is the one I downloaded like you said.

this is the one that I had to backup
-rwxrwxr-x  1 volumio volumio 14015076 Feb 28 15:19 librespot.bak

**Comment by nanomesher** [comment] 2018-03-18 15:44
For this problem in Android App 8.4.45.633 , Do we know if it's a bug or intended change in the Spotify App?

ios and windows 10 are working perfectly.

thanks!

**Comment by cortegedusage** [comment] 2018-03-18 15:51
@nanomesher
it's a bit weird, because reverting back to earlier versions doesn't seem to work...

my wife and coworkers, who are on IOS aren't experiencing this... weird

**Comment by ashthespy** [comment] 2018-03-18 15:53
@cortegedusage 
`sudo journalctl | grep 'librespot'` 
you should find a line such as:
 `volumio[22507]: INFO:librespot: librespot 323aea3 (2018-03-17). Built on 2018-03-17. Build ID: WtYFXXWP`

**Comment by cortegedusage** [comment] 2018-03-18 15:58
@ashthespy  
Mar 18 15:34:02 woonkamer volumio[1521]: INFO:librespot: librespot 377b9ba (2018                                                                                                          -03-15). Built on 2018-03-15. Build ID: kqmCDKcO

**Comment by ashthespy** [comment] 2018-03-18 15:59
Or - just to make sure -- disable the plugin and
```
$ cd /data/plugins/music_service/volspotconnect2/
$ rm librespot
$ wget https://files.gitter.im/ashthespy/AuFk/librespot
$ chmod +x librespot
```

**Comment by ashthespy** [comment] 2018-03-18 16:03
In related news - I think it's time to make a separate repo for Volumio specific modifications of librespot ( Vollibrespot | VolumioSpotify | VolumioConnect | ?) and end the random binaries floating around in gitter space!

**Comment by cortegedusage** [comment] 2018-03-18 16:11
@ashthespy good Idea I'd vote for Volibrespot

apart from that.
Mar 18 16:06:27 woonkamer volumio[1563]: INFO:librespot: librespot 323aea3 (2018                                                                                                             -03-17). Built on 2018-03-17. Build ID: WtYFXXWP

is what I'm on now same as yours running PI3 ... anyhow behaviour is the same.. 
gonna make Pizza now for my kids..

cheers!

**Comment by mneedes** [comment] 2018-03-18 16:14
@cortedusage   I tried out the new librespot binary but I had to hack the startconnect.sh script to remove the ''--onstart" flag from the librespot command line (the new librespot doesn't support that option?).  Problem is, the volspotconnect2 plugin will rewrite that script sometimes so that change won't persist, however it did allow me to temporarily test the binary.   Unfortunately it didn't work for me -- but I didn't attempt to integrate #156 .  Maybe I need this also?

**Comment by cortegedusage** [comment] 2018-03-18 16:20
#156 doesnt have onstart in startconnect.sh aparently.
thanks for the tip anyway

**Comment by ashthespy** [comment] 2018-03-18 16:26
@mneedes  I add my changes into [`volspotconnect2.zip`](https://files.gitter.im/ashthespy/Xrht/volspotconnect2.zip) 

But, lets wait for balbuze to test out - he also reported seeing these issues with the Android client


PS: *seems* to work here! This is after 8 Next/Prev from both the App and the WebUI.
![image](https://user-images.githubusercontent.com/16233271/37568116-fda6964e-2ad0-11e8-908a-94489f507b56.png)

**Comment by cortegedusage** [comment] 2018-03-18 19:44
@ashthespy  
I believe you put the wrong librespot in that zip 
because it has the wrong date, from somewhere in februari.

replacing it with the new one doesn't do anything.

apart from that the volume normalisation flag doesn't work.
if I remove that from the .tmpl it starts else it won't.
(should be giving an error in the gui, but that's not your problem)

something seems wrong because if I add it by hand it works as expected (volume normalization)

But still having the same issues...

**Comment by cortegedusage** [comment] 2018-03-18 19:45
on a side note I might say that in the plugin manager it says it is version 0.6.4

**Comment by balbuze** [comment] 2018-03-18 20:02
@cortegedusage  I just uploaded a dev version with all the last mod. Let us know how it works.

**Comment by cortegedusage** [comment] 2018-03-18 21:20
@balbuze & @ashthespy 
You did it again... It seems to work. I will listen to music all night.
So I will test it on the fly.

**Comment by cortegedusage** [comment] 2018-03-18 21:25
some new behaviour is that there is a 5 second delay between stopping mpd and
playing librespot. Is this intentional?
the other way around works now.

**Comment by cortegedusage** [comment] 2018-03-18 21:30
Ok the delay is only there when pushing play on the app.
when MPD is playing and I push next song on the app, it stops mpd and plays instantly the next song.

and I'm getting occasional alsa busy errors, this is occasionally when switching from librespot to mpd, by clicking on a song.

**Comment by cortegedusage** [comment] 2018-03-18 22:02
and apart from that the time on the app isn't always sync with the real time, it takes some time to 
get started, if it starts at all.. didn't see a pattern yet.

**Comment by ashthespy** [comment] 2018-03-18 22:17
@cortegedusage There are few limitations of the current hooks I've exposed in librespot. But, I have a PR over at librespot that should make the hooks exposed to Volumio more consistent and reliable. Then the UI stuff becomes trivial to solve.  This limitation leads to a small check to determine if Volspotconnect is the active service before  pushing the state - else the Volumio state machine rejects it leading to other issues (Alsa busy, time syncing, etc)

I know it's not perfect - but we are working on it! :-)

**Comment by cortegedusage** [comment] 2018-03-18 22:21
ah ok, well not perfect is good enough for me!
you got it working again.
you guys rock!

**Comment by mneedes** [comment] 2018-03-19 17:12
The volspotconnect2.zip provided by ash solves my Android sync issues.
Great job!  Thanks.
Matt

**Comment by ashthespy** [comment] 2018-03-19 17:23
@mneedes my zip was an unofficial quick test package, please switch to the dev version from this repo - it has more goodness in there ;-)

**Closed** 2018-03-21 18:14 UTC

**Comment by amundhov** [comment] 2019-02-26 16:25
Sorry to revive an old thread, but I experience this exact issue. Has the sync fix not made it into volumio distribution yet?
